# -*- coding: utf-8 -*-
"""Deep_learning_Lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11tKBrNFby2bJAXdgzLZ-NsZXIKEFIQuA
"""

pip install tensorflow

import tensorflow as tf
print(tf.__version__)

a = tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

m=tf.constant([[1,2,3],[4,5,6]])
print(m)

t3=tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])
print(t3)

"""Tensor Addition

"""

a = tf.constant([10,20,30])
b = tf.constant([50,60,70])

print(a+b)



"""Addition of scalars"""

a = tf.constant(10)
b = tf.constant(20)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)



"""Vector Addititon"""

a = tf.constant([1,2])
b = tf.constant([3,2])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)



"""addititon of 2-D Vectors"""

a = tf.constant([[1,2],[1,2]])
b = tf.constant([[2,1],[2,1]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)



"""Data types, shape , number of dimensions

"""

t= tf.constant([[1, 2, 3],[4, 5, 6]])
print(t.dtype)
print(t.shape)
print(t.ndim)

import numpy as np

numpy_array = np.array([10, 20, 30, 40])

tensor = tf.convert_to_tensor(numpy_array)

print("NumPy Array:",numpy_array)


print("\nTensorFlow Tensor:",tensor)

